# Generated by Django 4.2 on 2025-05-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiMember',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('seq', models.BigAutoField(db_comment='레코드 인덱스', primary_key=True, serialize=False)),
                ('id', models.CharField(db_comment='사용자 ID', max_length=20, unique=True)),
                ('name', models.CharField(db_comment='사용자 이름', max_length=20)),
                ('grade_code', models.CharField(db_comment='사용자 등급 코드(ni_code:001 참고)', max_length=6)),
                ('email', models.CharField(blank=True, db_comment='사용자 이메일', max_length=70, null=True)),
                ('tel', models.CharField(blank=True, db_comment='전화', max_length=13, null=True)),
                ('phone', models.CharField(blank=True, db_comment='사용자 전화번호', max_length=13, null=True)),
                ('state', models.CharField(db_comment='사용자 상태(y:활성, n:비활성)', max_length=1)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록 일시')),
                ('upd_dt', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('lastlogin_dt', models.DateTimeField(blank=True, db_comment='마지막 로그인 일시', null=True)),
                ('fcm_use', models.CharField(db_comment='fcm 사용 여부(y:사용, n:미사용)', default='n', max_length=1)),
                ('position', models.CharField(blank=True, db_comment='직책', max_length=100, null=True)),
                ('appointment', models.CharField(blank=True, db_comment='직위', max_length=100, null=True)),
                ('department', models.CharField(blank=True, db_comment='부서', max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.')),
            ],
            options={
                'db_table': 'ni_member',
                'db_table_comment': '사용자 정보 테이블',
                'managed': False,
            },
        ),
    ]
